[package]
name = "az-pdd"
version = "0.1.0"
authors = ["Peter Lamby <peterlamby@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
